### ISSUE TITLE
Actions: macOS 12 (Monterey) on GitHub-hosted runners

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#227]
**Summary**
Actions will add the ability to run your workflow jobs on the latest macOS version from Apple, Monterey. Apple is expected to [release macOS Monterey this fall](https://www.apple.com/macos/monterey-preview/).

**Intended Outcome**
Run your Actions workflow jobs on the latest iteration of Apple's macOS platform.

**How will it work**
Update your workflow jobs to include `runs-on: macos-11`

```
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
