### ISSUE TITLE
Actions: Windows Server 2022 on GitHub-hosted runners

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#241]
Windows Server 2022 with [Visual Studio 2022 Preview](https://visualstudio.microsoft.com/vs/preview/) is now available in beta on GitHub-hosted runners. Use it by putting `runs-on: windows-2022` in your workflow file.

```
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build
      - name: Run tests
        run: dotnet test
```

The Windows Server 2022 runner image has [different tools and tool versions ](https://github.com/actions/virtual-environments/issues/3949)than Windows Server 2019.

Read more on available runner images and beta images terms of use in [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
