### ISSUE TITLE
Actions: macOS 11 on GitHub-hosted runners

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#242]
macOS 11 Big Sur is now generally available on GitHub-hosted runners. Use GitHub Actions to build and publish apps for the latest Apple ecosystem by updating your workflows to include `runs-on: macos-11`

```
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```

The macOS 11 Big Sur runner image has different tools and tool versions than macOS 10.15 Catalina. See the [full list](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) of changed software.

If you spot any issues with your workflows when using Big Sur, please let us know by creating an issue in the [virtual-environments repository.](https://github.com/actions/virtual-environments)
