### ISSUE TITLE
Actions: macOS 12 (Monterey) is now generally available for GitHub-hosted runners 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#513]
### Summary

Actions will add the ability to run your workflow jobs on the latest macOS version from Apple, Monterey.  

### Intended Outcome

Run your Actions workflow jobs on the latest iteration of Apple's macOS platform.

### How will it work?

Update your workflow jobs to include `runs-on: macos-12`

```
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
