### ISSUE TITLE
Actions: macOS 14 on GitHub-hosted runners (Public Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#813]
### Summary

Actions will add the ability to run your workflow jobs on the latest macOS version from Apple. 

### Intended Outcome

Apple developers require the latest version of macOS and Xcode. 

### How will it work?

Update your workflows to include `runs-on: macos-14` or `runs-on: macos-14-xl`

```
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
