### ISSUE TITLE
Actions: macOS 13 (Ventura) on GitHub-hosted runners (GA) 

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#814]
### Summary

Actions will add the ability to run your workflow jobs on the latest macOS version from Apple, Ventura.

### Intended Outcome

Apple developers require the latest version of macOS and Xcode to build their software. 

### How will it work?

**How will it work**
Update your workflows to include `runs-on: macos-13` or `runs-on: macos-13-xl`

```
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
