### ISSUE TITLE
Actions: macOS 14 (Sonoma) is generally available and the `latest` macOS runner image

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#926]
### Summary

macOS 14 is now generally available for GitHub-hosted runners. It will also become the `latest` macOS runner image with workflows migrating from April 2024 through June 2024. 

### Intended Outcome

Apple developers require the latest version of macOS and Xcode.

### How will it work?

Actions workflows using the `macos-latest` label will incrementally transition from macOS 12 to macOS 14 beginning April 8th 2024 and will conclude before the end of June 2024. This also applies to larger macOS runners, for which the following YAML workflow labels can be used: 

- `macos-latest-xlarge`
- `macos-latest-large` 

```
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```

To use macOS 14 directly, update your workflows to include `runs-on: macos-14`, `runs-on: macos-14-xlarge`, or `runs-on: macos-14-large`

```
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
