### ISSUE TITLE
Actions: Ubuntu 24 on GitHub-hosted runners (GA)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#980]
### Summary

Actions will add the ability to run your workflow jobs on the latest Ubuntu 24.04 version from Canonical.  With this release the Ubuntu 24 image will also become the `latest` Ubuntu runner image with workflows migrating in September 2024.

### Intended Outcome

Developers will be able to build and test their code on the latest version of Ubuntu, while using the `latest` tag within their Actions job

### How will it work?

Actions workflows using the `ubuntu-latest` label will incrementally transition from Ubuntu 22 to Ubuntu 24 beginning September 2024.

To use the Ubuntu 24 image directly, update the `runs-on:` key in you workflow file to `ubuntu-24.04`
To run on the `-latest` tag, use the `ubuntu-latest` label.

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization
```
