### ISSUE TITLE
Actions: macOS 15 is now available for GitHub-hosted runners (GA)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#986]
### Summary

macOS 15 is now generally available for GitHub-hosted runners. It will also become the `latest` macOS runner image with workflows migrating from November 2024 through December 2024. 

### Intended Outcome

Apple developers require the latest version of macOS and Xcode now have access to newer versions

### How will it work?

Actions workflows using the `macos-latest` label will incrementally transition from macOS 14 to macOS 15 beginning November 2024 and will conclude before the end of December 2024. This also applies to larger macOS runners, for which the following YAML workflow labels can be used: 

- `macos-latest-xlarge`
- `macos-latest-large` 

```
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```

To use macOS 15 directly, update the `runs-on:` key in you workflow file to `macos-15`, `macos-15-large`, or `macos-15-xlarge`

```
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
