### ISSUE TITLE
Actions: macOS 15 is now available for GitHub-hosted runners (Public Beta)

### ISSUE THREAD

**Issue by github-product-roadmap** [github/roadmap#987]
### Summary

macOS 15 is now available in public beta for GitHub-hosted runners. 

### Intended Outcome

Apple developers require the latest version of macOS and Xcode now have access to newer versions

### How will it work?

Update the `runs-on:` key in you workflow file to `macos-15`, `macos-15-large`, or `macos-15-xlarge`

```
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
```
